apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blazorapp
  template:
    metadata:
      labels:
        app: blazorapp
    spec:
      containers:
        - name: blazorapp
          image: blazorapp1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/app/keys"
              name: dataprotection-storage
      volumes:
        - name: dataprotection-storage
          persistentVolumeClaim:
            claimName: blazorapp-dataprotection-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapplication3
  template:
    metadata:
      labels:
        app: webapplication3
    spec:
      containers:
        - name: webapplication3
          image: webapplication3:latest 
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DOTNET_RUNNING_IN_CONTAINER
              value: "true"
