apiVersion: v1
kind: Service
metadata:
  name: blazorapp-service
spec:
  type: NodePort
  selector:
    app: blazorapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 

---


---
apiVersion: v1
kind: Service
metadata:
  name: webapplication3-service
spec:
  selector:
    app: webapplication3
  ports:
    - name: http
      protocol: TCP
      port: 80  # External port
      targetPort: 8081  # Container port
